INSERT INTO EMPLOYEE(ID, COMPANY, PERSON_ID) VALUES (1, 'Pepsi', 101);
INSERT INTO EMPLOYEE(ID, COMPANY, PERSON_ID) VALUES (2, 'Google', 201);
INSERT INTO EMPLOYEE(ID, COMPANY, PERSON_ID) VALUES (3, 'Tesla', 301);

